language: c

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
      - kalakris-cmake
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install cmake; fi

# Build with Debug and Release to flush out build problems
script:
  - mkdir Debug
  - cd Debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make
  - cd ..
  - mkdir Release
  - cd Release
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make
