matrix:
  include:
   - language: node_js
     node_js:
     - "node"
   - language: python
     python:
       - "3.6"
     install:
       - pip install pipenv
       - pipenv install
       - sudo add-apt-repository ppa:mc3man/trusty-media
       - sudo apt-get update
       - sudo apt-get dist-upgrade
       - sudo apt-get install ffmpeg
     script:
       - python -m unittest discover server/tests
 
