matrix:
  include:
   - language: node_js
     node_js:
     - "node"
   - language: python
     python:
       - "3.6"
     install:
       - pip install pipenv
       - pipenv install
       - apt-get install ffmpeg
     script:
       - python -m unittest discover server/tests
 
