matrix:
  include:
   - language: node_js
     node_js:
     - "node"
   - language: python
     python:
       - "3.6"
     install:
       - pip install pipenv
       - pipenv install
     script:
       - python -m unittest discover server/tests
     env:
       - APIKEY=123456789
       - MICROSOFTKEY=123456789
       - MICROSOFTID=123456789
