matrix:
  include:
   - language: node_js
     node_js:
     - "node"
     deploy:
       provider: script
       script: python3 publishExtension.py
       on:
         branch: master
   - language: python
     python:
       - "3.6"
     install:
       - pip install pipenv
       - pipenv install
     script:
       - python -m unittest discover server/tests
 
